fixtures:
  repositories:
    "puppi": "git://github.com/Adaptavist/puppet-puppi.git"
    "monitor": "git://github.com/Adaptavist/puppet-monitor.git"
    "firewall": "git://github.com/Adaptavist/puppet-firewall.git"
    "iptables": "git://github.com/Adaptavist/puppet-iptables.git"
    "concat": "git://github.com/Adaptavist/puppet-concat.git"
  symlinks:
    "postfix": "#{source_dir}"

